version: "3.7"

services:
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/fae-draussen-ortung:${TAG}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - TZ=Europe/Berlin
      - SPRING_PROFILES_ACTIVE=prod
